# Generated by Django 6.1 on 2026-09-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(help_text='Posición del módulo en la ruta de aprendizaje (1, 2, 3...)')),
                ('icono', models.CharField(default='fa-solid fa-puzzle-piece', help_text='Clase de Font Awesome usada en el dashboard', max_length=50)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text='Afirmación a evaluar como Mito o Verdad', max_length=300)),
                ('es_verdad', models.BooleanField(help_text='True si la afirmación es VERDADERA, False si es un MITO')),
                ('explicacion', models.TextField(help_text='Texto que se muestra al usuario luego de responder')),
                ('completada', models.BooleanField(default=False, help_text='Indica si el usuario ya respondió correctamente')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo')),
            ],
        ),
    ]
