# Generated by Django 5.2.17 on 2026-09-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='es_verdad',
            field=models.BooleanField(help_text='True si es VERDADERA, False si es un MITO'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='explicacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='pregunta',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.CharField(default='fa-solid fa-puzzle-piece', help_text='Clase de Font Awesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='orden',
            field=models.PositiveIntegerField(help_text='Posición del módulo (1, 2, 3...)'),
        ),
    ]
